import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  DeleteObjectCommand,
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';

/**
 * Where attachment bytes actually live.
 *
 * A 5S programme runs on photographs: a red tag is a claim until there is a
 * picture of the item, and an audit score is an opinion until the before and
 * after shots sit beside it. Until now those bytes were written to a directory
 * inside the container, which does not survive the container being replaced —
 * so a redeploy quietly destroyed the evidence while keeping every row that
 * points at it.
 *
 * The store is an interface with two implementations because both are real
 * situations: a single machine at a customer's site with a mounted volume, and
 * an object store (S3, or MinIO on their own hardware) where the bytes outlive
 * any particular container.
 *
 * Keys are generated by `buildStorageKey` — a random id plus an extension
 * derived from the sniffed type — so nothing a client sends reaches a path or
 * an object name.
 */
export interface AttachmentStore {
  put(key: string, bytes: Buffer, mimeType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  /** Resolves whether or not the object was there; see the service. */
  remove(key: string): Promise<void>;
  /** For the startup log, so an operator can see which store is in use. */
  describe(): string;
}

/** The token the module provides the chosen store under. */
export const ATTACHMENT_STORE = 'ATTACHMENT_STORE';

/**
 * Bytes on a local disk.
 *
 * Correct for a single machine with a real volume mounted at `UPLOAD_DIR`, and
 * the default because it needs nothing to be set up. The root is resolved once
 * so a key can never be joined into an escape.
 */
export class LocalAttachmentStore implements AttachmentStore {
  constructor(private readonly root: string) {}

  private path(key: string) {
    return join(this.root, key);
  }

  async put(key: string, bytes: Buffer) {
    await mkdir(this.root, { recursive: true });
    await writeFile(this.path(key), bytes);
  }

  get(key: string) {
    return readFile(this.path(key));
  }

  async remove(key: string) {
    await unlink(this.path(key));
  }

  describe() {
    return `local disk at ${this.root}`;
  }
}

/**
 * Bytes in an S3-compatible object store.
 *
 * `S3_ENDPOINT` and path-style addressing are what make this work against
 * MinIO or Ceph on a customer's own hardware, which is the realistic shape of
 * a deployment at a plant that will not send its floor photographs to a public
 * cloud.
 *
 * Credentials are left to the SDK's own chain when none are configured, so an
 * instance role or a mounted credentials file works without this code knowing
 * about it — and there is no path where a secret has to be written down twice.
 */
export class S3AttachmentStore implements AttachmentStore {
  constructor(
    private readonly client: Pick<S3Client, 'send'>,
    private readonly bucket: string,
    private readonly where = 's3',
  ) {}

  async put(key: string, bytes: Buffer, mimeType: string) {
    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: key,
        Body: bytes,
        ContentType: mimeType,
      }) as never,
    );
  }

  async get(key: string) {
    const response = (await this.client.send(
      new GetObjectCommand({ Bucket: this.bucket, Key: key }) as never,
    )) as { Body?: { transformToByteArray?: () => Promise<Uint8Array> } };

    const body = response?.Body;

    if (!body?.transformToByteArray) {
      throw new Error(`Attachment ${key} came back without a body`);
    }

    return Buffer.from(await body.transformToByteArray());
  }

  async remove(key: string) {
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }) as never);
  }

  describe() {
    return `${this.where} bucket ${this.bucket}`;
  }
}

/**
 * The store this deployment is configured for.
 *
 * `ATTACHMENT_STORE=s3` switches; anything else keeps local disk. A missing
 * bucket is refused at startup rather than at the first upload: the failure
 * belongs where somebody is watching, not in the middle of an audit.
 */
export const createAttachmentStore = (configService: ConfigService): AttachmentStore => {
  const logger = new Logger('AttachmentStore');
  /*
    Defaults applied here rather than left to `get`'s second argument: a
    configuration that answers `undefined` — which is every stub in a test, and
    a real `ConfigService` asked for a key it has never heard of — would
    otherwise resolve a path from nothing.
  */
  const setting = (key: string, fallback: string) =>
    configService.get<string>(key) ?? fallback;
  const kind = setting('ATTACHMENT_STORE', 'local');

  if (kind !== 's3') {
    const store = new LocalAttachmentStore(resolve(setting('UPLOAD_DIR', './uploads')));
    logger.log(`Attachments are kept on ${store.describe()}`);

    return store;
  }

  const bucket = setting('S3_BUCKET', '');

  if (!bucket) {
    throw new Error('ATTACHMENT_STORE=s3 needs S3_BUCKET');
  }

  const endpoint = setting('S3_ENDPOINT', '');
  const accessKeyId = setting('S3_ACCESS_KEY_ID', '');
  const secretAccessKey = setting('S3_SECRET_ACCESS_KEY', '');

  const client = new S3Client({
    region: setting('S3_REGION', 'us-east-1'),
    ...(endpoint ? { endpoint } : {}),
    // MinIO and Ceph address buckets by path rather than by subdomain.
    forcePathStyle: configService.get<boolean>('S3_FORCE_PATH_STYLE') ?? Boolean(endpoint),
    // Nothing configured means the SDK's own chain: an instance role, a
    // mounted credentials file, or the environment it was given.
    ...(accessKeyId && secretAccessKey
      ? { credentials: { accessKeyId, secretAccessKey } }
      : {}),
  });

  const store = new S3AttachmentStore(client, bucket, endpoint || 's3');
  logger.log(`Attachments are kept in ${store.describe()}`);

  return store;
};
